# Native Windows Clang-CL (MSVC ABI), using MSYS2 binaries and xwin SDK.
set(HACHI_TC_ROOT "$ENV{HACHI_TC_ROOT}")
if(NOT HACHI_TC_ROOT)
    set(HACHI_TC_ROOT "E:/hjs-tc")
endif()
file(TO_CMAKE_PATH "${HACHI_TC_ROOT}" HACHI_TC_ROOT)
set(HACHI_LLVM "${HACHI_TC_ROOT}/packages/clang64/bin")
set(XWIN_ROOT "${HACHI_TC_ROOT}/sdk")
file(GLOB MSVC_DIRS LIST_DIRECTORIES TRUE "${XWIN_ROOT}/VC/Tools/MSVC/*")
file(GLOB SDK_DIRS LIST_DIRECTORIES TRUE "${XWIN_ROOT}/Windows Kits/10/Include/*")
list(SORT MSVC_DIRS COMPARE NATURAL ORDER DESCENDING)
list(SORT SDK_DIRS COMPARE NATURAL ORDER DESCENDING)
if(NOT MSVC_DIRS OR NOT SDK_DIRS)
    message(FATAL_ERROR "xwin SDK is missing under ${XWIN_ROOT}")
endif()
list(GET MSVC_DIRS 0 MSVC_DIR)
list(GET SDK_DIRS 0 SDK_DIR)
get_filename_component(HACHI_MSVC_VERSION "${MSVC_DIR}" NAME)
get_filename_component(SDK_VERSION "${SDK_DIR}" NAME)
set(CMAKE_C_COMPILER "${HACHI_LLVM}/clang-cl.exe")
set(CMAKE_CXX_COMPILER "${HACHI_LLVM}/clang-cl.exe")
set(CMAKE_LINKER "${HACHI_LLVM}/lld-link.exe")
set(CMAKE_AR "${HACHI_LLVM}/llvm-lib.exe")
set(CMAKE_RC_COMPILER "${HACHI_LLVM}/llvm-rc.exe")
set(CMAKE_MT "${HACHI_LLVM}/llvm-mt.exe")
set(CMAKE_MAKE_PROGRAM "${HACHI_LLVM}/ninja.exe" CACHE FILEPATH "")
set(HACHI_FLAGS "--target=x86_64-pc-windows-msvc /clang:-fuse-ld=lld /winsysroot${XWIN_ROOT} /vctoolsversion${HACHI_MSVC_VERSION} /winsdkversion${SDK_VERSION} /D_CRT_SECURE_NO_WARNINGS /D_SILENCE_ALL_CXX17_DEPRECATION_WARNINGS")
set(CMAKE_C_FLAGS_INIT "${HACHI_FLAGS}")
set(CMAKE_CXX_FLAGS_INIT "${HACHI_FLAGS}")
set(CMAKE_RC_FLAGS_INIT "/I\"${MSVC_DIR}/include\" /I\"${SDK_DIR}/ucrt\" /I\"${SDK_DIR}/shared\" /I\"${SDK_DIR}/um\"")
set(HACHI_LIBS "/libpath:\"${MSVC_DIR}/lib/x64\" /libpath:\"${XWIN_ROOT}/Windows Kits/10/Lib/${SDK_VERSION}/ucrt/x64\" /libpath:\"${XWIN_ROOT}/Windows Kits/10/Lib/${SDK_VERSION}/um/x64\"")
set(CMAKE_EXE_LINKER_FLAGS_INIT "${HACHI_LIBS}")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "${HACHI_LIBS}")
set(CMAKE_MODULE_LINKER_FLAGS_INIT "${HACHI_LIBS}")
# CMake's Windows defaults add /INCREMENTAL:YES to Debug try-compiles;
# lld-link treats it as a file unless it is explicitly disabled.
foreach(kind EXE SHARED MODULE)
    foreach(config DEBUG RELEASE RELWITHDEBINFO MINSIZEREL)
        set(CMAKE_${kind}_LINKER_FLAGS_${config} "/INCREMENTAL:NO" CACHE STRING "" FORCE)
    endforeach()
endforeach()
set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded" CACHE STRING "" FORCE)
set(CMAKE_TRY_COMPILE_PLATFORM_VARIABLES HACHI_TC_ROOT)
