"""Builds juce/src/PinyinTable.inc: one pinyin syllable for every Chinese
character the editor knows.

The readings are CC-CEDICT's, as carried by csharp-pinyin, which OpenUtau
ships embedded in its Pinyin.dll -- so this reads them out of that DLL rather
than downloading anything.  CC-CEDICT is licensed CC BY-SA 4.0; the table
generated from it is under the same licence, and says so at its top.

    python tools/make_pinyin_table.py [path/to/Pinyin.dll]

Per character: the first reading listed, which is the most common one --
polyphones are not told apart -- in lower case, with no tone, and with u
umlaut written v (lv, nv, lve, nve) the way UTAU voicebanks spell it.  After
j, q, x and y the umlaut is already written u in pinyin (qu, xue, yu), and so
it stays.  A traditional character the table does not list reads as its
simplified form does.
"""
import io
import os
import re
import struct
import sys
import unicodedata

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "juce", "src", "PinyinTable.inc")
DLL = sys.argv[1] if len(sys.argv) > 1 else "F:/OpenUtau/Pinyin.dll"


def resources(path):
    """Every embedded .NET resource, in order."""
    data = open(path, "rb").read()
    pe = struct.unpack_from("<I", data, 0x3C)[0]
    sections = struct.unpack_from("<H", data, pe + 6)[0]
    optional_size = struct.unpack_from("<H", data, pe + 20)[0]
    optional = pe + 24
    magic = struct.unpack_from("<H", data, optional)[0]
    directories = optional + (96 if magic == 0x10B else 112)
    cli_rva = struct.unpack_from("<I", data, directories + 14 * 8)[0]
    table = []
    for index in range(sections):
        header = optional + optional_size + index * 40
        virtual_size, virtual_address = struct.unpack_from("<II", data, header + 8)
        raw = struct.unpack_from("<I", data, header + 20)[0]
        table.append((virtual_address, virtual_size, raw))

    def offset(rva):
        for address, size, raw in table:
            if address <= rva < address + max(size, 1):
                return rva - address + raw
        raise ValueError("rva %x outside every section" % rva)

    cli = offset(cli_rva)
    rva, size = struct.unpack_from("<II", data, cli + 24)
    base = offset(rva)
    position = 0
    blobs = []
    while position + 4 <= size:
        length = struct.unpack_from("<I", data, base + position)[0]
        if length > size:
            break
        blobs.append(data[base + position + 4: base + position + 4 + length])
        position = (position + 4 + length + 7) & ~7
    return blobs


def pairs(blob):
    for line in blob.decode("utf-8").splitlines():
        if ":" in line:
            key, value = line.split(":", 1)
            yield key, value


def plain(reading):
    """A reading with its tone taken off, u umlaut written v."""
    text = unicodedata.normalize("NFD", reading.strip().lower())
    text = text.replace("u\u0308", "v")
    text = "".join(ch for ch in text if not 0x300 <= ord(ch) <= 0x36F)
    return text


blobs = resources(DLL)
starts = [index for index, blob in enumerate(blobs)
          if blob.startswith(b"The Mandarin dictionary files")]
if not starts:
    sys.exit("no Mandarin dictionary in %s" % DLL)
licence = blobs[starts[0]].decode("utf-8")
mandarin = blobs[starts[0] + 1:]
words = traditional = None
for blob in mandarin:
    lines = list(pairs(blob))
    if len(lines) < 1000:
        continue
    single = [(k, v) for k, v in lines if len(k) == 1]
    if len(single) < 0.9 * len(lines):
        continue
    if all(len(v) == 1 for _, v in single[:200]):
        traditional = dict(single)
    elif any(re.search("[a-z]", v) for _, v in single[:200]):
        words = dict(single)
if words is None or traditional is None:
    sys.exit("could not tell the character table and the traditional table apart")

readings = {}
for character, listed in words.items():
    first = plain(listed.split(",")[0])
    if re.fullmatch("[a-z]+", first) and ord(character) > 0x7F:
        readings[ord(character)] = first
for character, simplified in traditional.items():
    code = ord(character)
    if code > 0x7F and code not in readings and ord(simplified) in readings:
        readings[code] = readings[ord(simplified)]

syllables = sorted(set(readings.values()))
index = {syllable: position for position, syllable in enumerate(syllables)}
with io.open(OUT, "w", encoding="utf-8", newline="\n") as out:
    out.write("// Generated by tools/make_pinyin_table.py -- do not edit by hand.\n")
    out.write("//\n")
    out.write("// Mandarin readings from CC-CEDICT, as carried by csharp-pinyin (the\n")
    out.write("// dictionary embedded in OpenUtau's Pinyin.dll).  CC-CEDICT is licensed\n")
    out.write("// Creative Commons Attribution-ShareAlike 4.0; this table, derived from\n")
    out.write("// it, is under the same licence.  Its notice, as shipped:\n//\n")
    for line in licence.strip().splitlines():
        out.write(("// " + line).rstrip() + "\n")
    out.write("\n")
    out.write("static const char* const pinyinSyllables[] = {\n")
    for position in range(0, len(syllables), 10):
        out.write("    " + " ".join('"%s",' % s for s in syllables[position:position + 10]) + "\n")
    out.write("};\n\n")
    out.write("// Code point, and the syllable it reads as, in code point order.\n")
    out.write("static const PinyinEntry pinyinEntries[] = {\n")
    entries = sorted(readings.items())
    for position in range(0, len(entries), 8):
        out.write("    " + " ".join("{ 0x%X, %d }," % (code, index[s])
                                     for code, s in entries[position:position + 8]) + "\n")
    out.write("};\n")
print("%d characters, %d syllables -> %s" % (len(readings), len(syllables), os.path.normpath(OUT)))
