"""Build lossless animation atlases from the four supplied transparent GIFs."""
from pathlib import Path
import shutil
from PIL import Image

root = Path(__file__).resolve().parents[1]
assets = root / 'juce/resources/note-dance'
assets.mkdir(parents=True, exist_ok=True)
sources = [('F1', '1789609568206.gif'), ('Eight', '1789609570935.gif'),
           ('F2', '1789609573303.gif'), ('Q', '1789609575392.gif')]
metadata = ['// Generated by tools/prepare-note-dance.py; timings are milliseconds.']
for name, filename in sources:
    original = assets / filename
    if not original.exists():
        shutil.copy2(root.parent / '图片素材' / filename, original)
    gif = Image.open(original)
    frames, durations = [], []
    for i in range(gif.n_frames):
        gif.seek(i)
        frames.append(gif.convert('RGBA'))
        durations.append(max(10, gif.info.get('duration', 100)))
    boxes = [f.getchannel('A').getbbox() for f in frames]
    left, right = min(b[0] for b in boxes), max(b[2] for b in boxes)
    width, height = right - left, max(b[3] - b[1] for b in boxes)
    atlas = Image.new('RGBA', (width * len(frames), height))
    for i, (frame, box) in enumerate(zip(frames, boxes)):
        # Keep the horizontal dance motion; anchor each frame's feet to the baseline.
        crop = frame.crop((left, box[1], right, box[3]))
        atlas.paste(crop, (i * width, height - crop.height))
    atlas.save(assets / f'dance{name}.png')
    ends, total = [], 0
    for duration in durations:
        total += duration
        ends.append(total)
    metadata.append(f'load({sources.index((name, filename))}, NoteDanceData::dance{name}_png, '
                    f'NoteDanceData::dance{name}_pngSize, {width}, {height}, '
                    '{' + ', '.join(map(str, ends)) + '});')
    print(name, len(frames), width, height, total)
(assets / 'frames.inc').write_text('\n'.join(metadata) + '\n', encoding='utf-8')
